version: '3.8'


services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "rivatent"
      POSTGRES_PASSWORD: "3223"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U rivatent -d mydb" ] #"pg_isready -U habrpguser -d habrdb"
        interval: 10s
        timeout: 5s
        retries: 5

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./user-service/.env
    depends_on:
       postgres:
         condition: service_healthy

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#
#  kafka:
#    image: wurstmeister/kafka:latest
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
#      KAFKA_ZOOKEEPER: zookeeper:2181
#    ports:
#      - "9094:9094"

#  zookeeper:
#    image: wurstmeister/zookeeper:latest
#    ports:
#      - "2181:2181"